import os
import hashlib
import logging

logger = logging.getLogger("solomon.trust.pcr")

class PCRValidator:
    """
    Platform Configuration Registers Validator.
    Checks boot seed parameters and files to detect system tampering.
    """
    def __init__(self, token_path: str = "./data/boot_token.bin"):
        self.token_path = token_path

    def validate_boot_integrity(self) -> bool:
        """
        Validates the boot token and files.
        On Windows, in production, we would invoke the BCrypt APIs or TBS.
        Here we check for the persistent boot token generated by the Rust auth crate.
        """
        logger.info("Running platform PCR validation checks...")
        
        # Locate the local fallback boot token or check production path
        target_path = self.token_path
        if not os.path.exists(target_path):
            # Fall back to root relative data directory if run from subdir
            target_path = os.path.join(os.getcwd(), "data", "boot_token.bin")
            
        if not os.path.exists(target_path):
            logger.warning(f"Boot token file not found at '{target_path}'. System unbooted or in debug fallback.")
            return False
            
        try:
            # Read token seed
            with open(target_path, "rb") as f:
                seed = f.read()
                
            if len(seed) != 32:
                logger.error("Boot token seed length is invalid.")
                return False
                
            # Simulate PCR hash check (verifying firmware/system files haven't changed)
            hasher = hashlib.sha256()
            hasher.update(seed)
            hasher.update(b"firmware-v1.0.0-pcr-0")
            digest = hasher.hexdigest()
            
            logger.info(f"Boot integrity verified. Derived PCR digest: {digest[:16]}...")
            return True
        except Exception as e:
            logger.error(f"PCR validation encountered an error: {e}")
            return False
